### ISSUE TITLE
RS2LoginProtocolDecoder redundant lock

### ISSUE THREAD

**Issue by Major-** [Zap-Framework/Zap#1]
Aside from the daft class name (also you should be throwing an IllegalStateException for the default case of the switch statement), there's a lock that does nothing in your login method:

```
    synchronized (new Object()) {
        player.initialize();
        player.initialized = true;
    }
```

synchronize the player instead (if you even need to synchronize here...)

Also use mutators instead of direct access, access states exist for a reason (and it looks nicer).

Finally:
Not sure why the player needs to have a client version field (particularly as your world is a singleton).
It's not an rsa opcode, that class should be IsaacCipher not ISAAC.
Not sure why you have a 'setPlayerName' method and also a 'playerName2' field...
'player.playerPass' (and 'player.playerName', 'player.playerRights' etc) are really dumb names, player.username, player.password, player.rights/privilege instead (and could be placed in a separate class)
Do all your start adding stuff in a separate place, shouldn't be placed in the login decoder.
You've got multiple 'if (returnCode == 2)' blocks
Use an enum for the player privilege instead of a field (also that check if it's equal to 3 is stupid)

**Comment by Faris-Mckay** [comment]
Thanks for the suggestions, a lot of the issues derived are actually from the netty implementation i'm using and having come around to sorting out the redundancies and optimizing it as i'd of preferred it just yet. I'd agree with all your issues highlighted here and will address them when I next get working on the Framework, do check back and see that its sorted out. 
The ISAAC thing is just the way I named the API, at the time I jarred the IssacCipher from Apollo I didn't actually know what a cipher was so I just named it isaac, and I'm just using that same dependency for this project.

**Comment by Faris-Mckay** [comment]
Also the world class isn't a singleton, it's re-instantiated to produce a multi-world effect, and so thats why i've added the client version.
Also to allow me to check which type of a client is being used for anti-cheat measures, which is low security but is worth adding in.

**Comment by Major-** [comment]
It is a singleton because you access it by Zap.getWorld() ...

**Comment by Faris-Mckay** [comment]
That returns the main world, I started off single worlded, but you'll notice theirs many getWorld methods which return different instances

**Comment by Major-** [comment]
Well you're registering the player in the main world by default, is this intentional? (also the 'main world' you're returning is the second world, arrays in java are zero-based).

**Comment by Faris-Mckay** [comment]
Yeah the players part is intentional it's supposed to fill the first world and then overspill in the world 2, w3,w4 ect. Quite naff but it's just supposed to be simple support for whoever wants to, to build on.
good find with the array, haven't programmed in so long I forget basics like that lol
